### ISSUE TITLE
Installation Issues / Latest Schema / Basestation Not Available

### ISSUE THREAD

**Issue by uppaljs** [Ysurac/FlightAirMap#11]
Hi @Ysurac 

I just pulled the latest from git , and am facing the following issues , and am unable to run FlightAirMap

**1. Basestation Not Available**
http://pp-sqb.mantma.co.uk/basestation_latest.zip is 404 now , I checked the main website and it seems that the supplier has taken this offline , do you happen to have a latest copy? If not , any other source to get it?

**2. Latest Schema Issue**
Whenever I am running cron-sbs.php after installation, I am getting the following error

php cron-sbs.php
You MUST update to latest schema. Run install/index.php

**3. Installation Issues**

Due to #1 in this list ,  The installation script fails , It also looks for install/tmp directory which doesn't exist.

The URL field in require/settings.php is important as otherwise rules / css doesn't load.

Please help.

Thanks,

**Comment by uppaljs** [comment]
for Issue number 2 , It seems that in require/class.Connection.php , $latest_schema = 5 , but in the check , its checking the database , which shows db/config.sql as version 2 , hence it fails , maybe a typo here?

**Comment by Ysurac** [comment]
All should be fixed now :
* An other source for BaseStation.sqb is used for now.
* Schema issue fixed (sorry)
* Installation should run.
URL field can be null if it's installed in website root directory (like my demo website).

**Comment by uppaljs** [comment]
Hi,

Thanks for the really quick response , I've updated it , I think db/updated_db.sh should also be updated with the new source for Basestation data.

**Also , Now i am getting the following error after most of the planes:**

php cron-sbs.php
Connecting to dump1090 ... Connected!
SCAN MODE

*********** New aircraft hex : 8961EC ***********
PHP Notice:  Undefined offset: 10 in /var/www/html/FlightAirMap/require/class.SBS.php on line 81
PHP Notice:  Undefined offset: 14 in /var/www/html/FlightAirMap/require/class.SBS.php on line 99
PHP Notice:  Undefined offset: 15 in /var/www/html/FlightAirMap/require/class.SBS.php on line 103
PHP Notice:  Undefined offset: 16 in /var/www/html/FlightAirMap/require/class.SBS.php on line 107
PHP Notice:  Undefined offset: 20 in /var/www/html/FlightAirMap/require/class.SBS.php on line 111
PHP Notice:  Undefined offset: 12 in /var/www/html/FlightAirMap/require/class.SBS.php on line 115
PHP Notice:  Undefined offset: 17 in /var/www/html/FlightAirMap/require/class.SBS.php on line 119
PHP Notice:  Undefined offset: 11 in /var/www/html/FlightAirMap/require/class.SBS.php on line 125
PHP Notice:  Undefined offset: 13 in /var/www/html/FlightAirMap/require/class.SBS.php on line 130
PHP Notice:  Undefined offset: 14 in /var/www/html/FlightAirMap/require/class.SBS.php on line 99
PHP Notice:  Undefined offset: 15 in /var/www/html/FlightAirMap/require/class.SBS.php on line 103
PHP Notice:  Undefined offset: 16 in /var/www/html/FlightAirMap/require/class.SBS.php on line 107
PHP Notice:  Undefined offset: 20 in /var/www/html/FlightAirMap/require/class.SBS.php on line 111
PHP Notice:  Undefined offset: 12 in /var/www/html/FlightAirMap/require/class.SBS.php on line 115
PHP Notice:  Undefined offset: 17 in /var/www/html/FlightAirMap/require/class.SBS.php on line 119
PHP Notice:  Undefined offset: 11 in /var/www/html/FlightAirMap/require/class.SBS.php on line 125
PHP Notice:  Undefined offset: 13 in /var/www/html/FlightAirMap/require/class.SBS.php on line 130

**The data being sent to cron-sbs.php from my receiver is the following**

Escape character is '^]'.
MSG,8,333,30,89610C,130,2015/04/18,06:11:43.832,2015/04/18,06:11:43.832,,,,,,,,,,,,0
MSG,3,333,37,89626D,137,2015/04/18,06:11:43.839,2015/04/18,06:11:43.839,,36000,,,26.88354,47.44943,,,0,0,0,0
MSG,4,333,37,89626D,137,2015/04/18,06:11:43.844,2015/04/18,06:11:43.844,,,383.0,272.2,,,0,,,,,
MSG,3,333,47,7103A1,147,2015/04/18,06:11:43.846,2015/04/18,06:11:43.846,,3425,,,24.89777,46.38143,,,0,0,0,0
MSG,3,333,31,71039A,131,2015/04/18,06:11:43.858,2015/04/18,06:11:43.858,,3450,,,24.92663,46.35463,,,0,0,0,0
MSG,4,333,25,8961EC,125,2015/04/18,06:11:43.876,2015/04/18,06:11:43.876,,,426.0,256.2,,,0,,,,,
MSG,8,333,30,89610C,130,2015/04/18,06:11:43.885,2015/04/18,06:11:43.885,,,,,,,,,,,,0
MSG,8,333,34,7608EA,134,2015/04/18,06:11:43.894,2015/04/18,06:11:43.894,,,,,,,,,,,,0
MSG,8,333,50,A9DD9E,150,2015/04/18,06:11:43.913,2015/04/18,06:11:43.913,,,,,,,,,,,,0
MSG,4,333,45,710083,145,2015/04/18,06:11:43.919,2015/04/18,06:11:43.919,,,508.0,117.4,,,64,,,,,
MSG,8,333,50,A9DD9E,150,2015/04/18,06:11:43.919,2015/04/18,06:11:43.919,,,,,,,,,,,,0
MSG,3,333,30,89610C,130,2015/04/18,06:11:43.923,2015/04/18,06:11:43.923,,30000,,,26.25925,48.46898,,,0,0,0,0

**in addition , plane pictures and planes types do not shop up at all**
I've attached a screenshot of the Latest activity page.

![flightmaperror](https://cloud.githubusercontent.com/assets/5232191/7214242/ccbf9e94-e5ab-11e4-8d0a-29237c4b574d.png)

**Comment by Ysurac** [comment]
Try commit 91eb391b409d8c423c7d6f8c1144cffd472dcee0
Maybe it will work, else we should see a debug message.

For plane pictures run update_db.php or install/index.php again. It use registration to find pics, and to find registration I use basestation.sqb

**Comment by uppaljs** [comment]
Hi,

Just updated again and below is the output , also , important to note that install/index.php is stuck at Populate database with externals data.... (Can be very slow)

Still don't get any pictures / Aircraft information as well.

!! Error in message : AIR,,333,1,71009C,101,2015/04/18,07:20:57.648,2015/04/18,07:20:57.648
*********** New aircraft hex : 71009C ***********
!! Error in message : AIR,,333,2,710054,102,2015/04/18,07:20:57.651,2015/04/18,07:20:57.651
!! Error in message : ID,,333,2,710054,102,2015/04/18,07:20:57.651,2015/04/18,07:20:57.651,SVA1024
*********** New aircraft hex : 710054 ***********
!! Error in message : AIR,,333,3,424174,103,2015/04/18,07:20:57.654,2015/04/18,07:20:57.654
!! Error in message : ID,,333,3,424174,103,2015/04/18,07:20:57.654,2015/04/18,07:20:57.654,KNE303
*********** New aircraft hex : 424174 ***********
!! Error in message : AIR,,333,4,896145,104,2015/04/18,07:20:57.658,2015/04/18,07:20:57.658
!! Error in message : ID,,333,4,896145,104,2015/04/18,07:20:57.658,2015/04/18,07:20:57.658,ETD653
!! Error in message : AIR,,333,5,894066,105,2015/04/18,07:20:57.692,2015/04/18,07:20:57.692
!! Error in message : ID,,333,5,894066,105,2015/04/18,07:20:57.692,2015/04/18,07:20:57.692,GFA911
*********** New aircraft hex : 894066 ***********
!! Error in message : AIR,,333,6,89407B,106,2015/04/18,07:20:57.697,2015/04/18,07:20:57.697
!! Error in message : ID,,333,6,89407B,106,2015/04/18,07:20:57.697,2015/04/18,07:20:57.697,GFA163
*********** New aircraft hex : 89407B ***********
!! Error in message : AIR,,333,7,896331,107,2015/04/18,07:20:57.700,2015/04/18,07:20:57.700
!! Error in message : ID,,333,7,896331,107,2015/04/18,07:20:57.700,2015/04/18,07:20:57.700,FDB611
*********** New aircraft hex : 896331 ***********
!! Error in message : AIR,,333,8,710044,108,2015/04/18,07:20:57.711,2015/04/18,07:20:57.711
!! Error in message : ID,,333,8,710044,108,2015/04/18,07:20:57.711,2015/04/18,07:20:57.711,SVA703
!! Error in message : AIR,,333,9,06A08A,109,2015/04/18,07:20:57.713,2015/04/18,07:20:57.713
!! Error in message : ID,,333,9,06A08A,109,2015/04/18,07:20:57.713,2015/04/18,07:20:57.713,QTR424
*********** New aircraft hex : 06A08A ***********
!! Error in message : AIR,,333,10,A99634,110,2015/04/18,07:20:57.721,2015/04/18,07:20:57.721
!! Error in message : ID,,333,10,A99634,110,2015/04/18,07:20:57.721,2015/04/18,07:20:57.721,N717BN
*********** New aircraft hex : A99634 ***********
!! Error in message : AIR,,333,11,06A018,111,2015/04/18,07:20:57.728,2015/04/18,07:20:57.728
!! Error in message : ID,,333,11,06A018,111,2015/04/18,07:20:57.728,2015/04/18,07:20:57.728,QTR1397
!! Error in message : AIR,,333,12,06414E,112,2015/04/18,07:20:57.761,2015/04/18,07:20:57.761
!! Error in message : ID,,333,12,06414E,112,2015/04/18,07:20:57.761,2015/04/18,07:20:57.761,ARA106
*********** New aircraft hex : 06414E ***********
!! Error in message : AIR,,333,13,8961E8,113,2015/04/18,07:20:57.778,2015/04/18,07:20:57.778
!! Error in message : ID,,333,13,8961E8,113,2015/04/18,07:20:57.778,2015/04/18,07:20:57.778,ETD93
*********** New aircraft hex : 8961E8 ***********
!! Error in message : AIR,,333,14,710380,114,2015/04/18,07:20:57.809,2015/04/18,07:20:57.809
!! Error in message : ID,,333,14,710380,114,2015/04/18,07:20:57.809,2015/04/18,07:20:57.809,803
*********** New aircraft hex : 710380 ***********
!! Error in message : AIR,,333,15,71001A,115,2015/04/18,07:20:57.816,2015/04/18,07:20:57.816
!! Error in message : ID,,333,15,71001A,115,2015/04/18,07:20:57.816,2015/04/18,07:20:57.816,SVA917
*********** New aircraft hex : 71001A ***********
*********** New aircraft hex : 06A018 ***********
!! Error in message : AIR,,333,16,71008E,116,2015/04/18,07:20:57.845,2015/04/18,07:20:57.845
!! Error in message : ID,,333,16,71008E,116,2015/04/18,07:20:57.845,2015/04/18,07:20:57.845,SVA1110
*********** New aircraft hex : 71008E ***********
*********** New aircraft hex : 896145 ***********
!! Error in message : AIR,,333,17,4CC3ED,117,2015/04/18,07:20:57.870,2015/04/18,07:20:57.870
!! Error in message : ID,,333,17,4CC3ED,117,2015/04/18,07:20:57.870,2015/04/18,07:20:57.870,SVA964
!! Error in message : AIR,,333,18,7608F0,118,2015/04/18,07:20:57.876,2015/04/18,07:20:57.876
!! Error in message : ID,,333,18,7608F0,118,2015/04/18,07:20:57.876,2015/04/18,07:20:57.876,PIA756
*********** New aircraft hex : 7608F0 ***********
!! Error in message : AIR,,333,19,706007,119,2015/04/18,07:20:57.923,2015/04/18,07:20:57.923
*********** New aircraft hex : 706007 ***********
*********** New aircraft hex : 710044 ***********
!! Error in message : AIR,,333,20,A3E89A,120,2015/04/18,07:20:57.954,2015/04/18,07:20:57.954
!! Error in message : ID,,333,20,A3E89A,120,2015/04/18,07:20:57.954,2015/04/18,07:20:57.954,CMB579
!! Error in message : AIR,,333,21,06A0A8,121,2015/04/18,07:20:57.956,2015/04/18,07:20:57.956
!! Error in message : ID,,333,21,06A0A8,121,2015/04/18,07:20:57.956,2015/04/18,07:20:57.956,QTR1399
*********** New aircraft hex : 06A0A8 ***********
!! Error in message : AIR,,333,22,894023,122,2015/04/18,07:20:58.022,2015/04/18,07:20:58.022
!! Error in message : AIR,,333,23,8960BA,123,2015/04/18,07:20:58.023,2015/04/18,07:20:58.023
!! Error in message : ID,,333,23,8960BA,123,2015/04/18,07:20:58.023,2015/04/18,07:20:58.023,ETD604
!! Error in message : AIR,,333,24,06A192,124,2015/04/18,07:20:58.050,2015/04/18,07:20:58.050
!! Error in message : ID,,333,24,06A192,124,2015/04/18,07:20:58.050,2015/04/18,07:20:58.050,QTR8244
*********** New aircraft hex : 06A192 ***********
!! Error in message : AIR,,333,25,89406E,125,2015/04/18,07:20:58.060,2015/04/18,07:20:58.060
!! Error in message : ID,,333,25,89406E,125,2015/04/18,07:20:58.060,2015/04/18,07:20:58.060,GFA941
*********** New aircraft hex : 89406E ***********
!! Error in message : AIR,,333,26,76096C,126,2015/04/18,07:20:58.062,2015/04/18,07:20:58.062
!! Error in message : ID,,333,26,76096C,126,2015/04/18,07:20:58.062,2015/04/18,07:20:58.062,SAI736
*********** New aircraft hex : 76096C ***********
*********** New aircraft hex : A3E89A ***********
*********** New aircraft hex : 4CC3ED ***********
!! Error in message : AIR,,333,27,8963AB,127,2015/04/18,07:20:58.226,2015/04/18,07:20:58.226
!! Error in message : ID,,333,27,8963AB,127,2015/04/18,07:20:58.226,2015/04/18,07:20:58.226,ETD535
*********** New aircraft hex : 8963AB ***********
!! Error in message : AIR,,333,28,06A248,128,2015/04/18,07:20:58.309,2015/04/18,07:20:58.309
!! Error in message : ID,,333,28,06A248,128,2015/04/18,07:20:58.309,2015/04/18,07:20:58.309,LHOB240
!! Error in message : AIR,,333,29,7335AF,129,2015/04/18,07:20:58.493,2015/04/18,07:20:58.493
*********** New aircraft hex : 7335AF ***********
*********** New aircraft hex : 06A248 ***********
!! Error in message : AIR,,333,30,894065,130,2015/04/18,07:20:59.981,2015/04/18,07:20:59.981
!! Error in message : ID,,333,30,894065,130,2015/04/18,07:20:59.981,2015/04/18,07:20:59.981,GFA187
*********** New aircraft hex : 894065 ***********
*********** New aircraft hex : 894023 ***********

**Comment by Ysurac** [comment]
In commit 8e5cf5d77e944d5dd22229a6a598f927ea022bb6 these messages are now ignored. What is your SBS source ?

Try to run install/update_db.php we will see where it's stuck. Without database populated picture can't be downloaded. Data from BaseStation.sqb populate aircraft_modes table in DB (else I only download routes and a translation table).

**Comment by uppaljs** [comment]
Hi,

My data source is FR24 receiver which they have sent to me to increase coverage - I'd essentially like to use that - I can stream the feed over to you using modesmixer2 if you'd like to check it out?

**Comment by Ysurac** [comment]
No it's ok, I only never saw these AIR and ID messages.
